ALTER TABLE cash_registers
ADD COLUMN IF NOT EXISTS total_sales_cash DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_sales_digital DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_ingresos DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_egresos DECIMAL(10, 2) DEFAULT 0;
